# Generated by Django 3.0.4 on 2020-03-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(verbose_name='Age of the person')),
                ('weight', models.IntegerField(verbose_name='weight of the person')),
                ('height', models.IntegerField(verbose_name='height of the person')),
                ('phone', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='phone no')),
                ('date_joined', models.DateField(verbose_name='Date joined')),
                ('address', models.CharField(max_length=500)),
                ('duration', models.IntegerField(verbose_name='subscription duration')),
                ('payment_status', models.BooleanField(default=True, verbose_name='subscribed or not')),
                ('photo', models.URLField(verbose_name='image url')),
            ],
        ),
    ]
