# Generated by Django 3.0.4 on 2020-03-17 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(verbose_name='Age of the person')),
                ('weight', models.IntegerField(verbose_name='weight of the person')),
                ('height', models.IntegerField(verbose_name='height of the person')),
                ('duration', models.IntegerField(verbose_name='subscription duration')),
                ('phone', models.IntegerField(max_length=10, verbose_name='phone no')),
                ('date_joined', models.DateField(verbose_name='Date joined')),
                ('exp_date', models.DateField(verbose_name='Date renewed')),
                ('address', models.CharField(max_length=500)),
                ('payment_status', models.BooleanField(default=True, verbose_name='subscribed or not')),
                ('photo', models.FileField(null=True, upload_to='')),
                ('renew_date', models.DateField(verbose_name='Date renewed')),
            ],
        ),
    ]
