# Generated by Django 3.0.4 on 2020-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_member_renew_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.FloatField(verbose_name='height of the person'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.FloatField(verbose_name='weight of the person'),
        ),
    ]
